### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by Unipara** [DHDAXCW/GL.iNet_GL-MT6000_lede#4]
Thanks for your contribution! Can you release 2023.12.08 docker version? I appreciated it. 

All the best,

Unipara

**Comment by DHDAXCW** [comment]
I need to test it for a while, and if there is no problem, I will release it. I will release it probably tomorrow.

**Comment by Unipara** [comment]
> I need to test it for a while, and if there is no problem, I will release it. I will release it probably tomorrow.

Thanks for this! You are the best.

Is that possible to get Tor on the service list?
